---
title: "using the vcf package"
author: "Kingsley"
date: "31/03/2021"
output: html_document
---

```{r,setup}
if (!requireNamespace("BiocManager", quietly=TRUE))
+     install.packages("BiocManager")
 BiocManager::install("intansv")
library("intansv")
```

## Introduction

This is a package of Vcf tools meant to execute codes in Rmarkdown

```{r cars}
breakdancer.file.path <- system.file ("extdata/ZS97.breakdancer.sv",
                                package = "intansv")
breakdancer.file.path
"/tmp/RtmpTNVj6Y/Rinst4ae7115d3df6/intansv/extdata/ZS97.breakdancer.sv"
breakdancer <- readBreakDancer(breakdancer.file.path)
str(breakdancer)
```

## Predictions of different programs

```{r, chunk1}
cnvnator.dir.path <- system.file("extdata/cnvnator", package="intansv")
cnvnator.dir.path
"/tmp/RtmpTNVj6Y/Rinst4ae7115d3df6/intansv/extdata/cnvnator"
cnvnator <- readCnvnator(cnvnator.dir.path)
str(cnvnator)
```

```{r, chunk2}
svseq.dir.path <- system.file("extdata/svseq2", package="intansv")
svseq.dir.path
"/tmp/RtmpTNVj6Y/Rinst4ae7115d3df6/intansv/extdata/svseq2"
svseq <- readSvseq(svseq.dir.path)
str(svseq)
```

```{r, chunk3}
delly.file.path <- system.file("extdata/ZS97.DELLY.vcf", package = "intansv") 
delly.file.path
"/tmp/RtmpTNVj6Y/Rinst4ae7115d3df6/intansv/extdata/ZS97.DELLY.vcf"
delly <- readDelly(delly.file.path)
str(delly)
```

```{r, chunk4}
pindel.dir.path <- system.file("extdata/pindel", package = "intansv")
pindel.dir.path
"/tmp/RtmpTNVj6Y/Rinst4ae7115d3df6/intansv/extdata/pindel"
pindel <- readPindel(pindel.dir.path)
str(pindel)
```

```{r,chunk5}
lumpy.file.path <- system.file("extdata/ZS97.LUMPY.vcf",                    package="intansv")
lumpy.file.path
"/tmp/RtmpTNVj6Y/Rinst4ae7115d3df6/intansv/extdata/ZS97.LUMPY.vcf"
lumpy <- readLumpy(lumpy.file.path)
str(lumpy)
```

```{r, chunk6}
softSearch.file.path <- system.file("extdata/ZS97.softsearch", package = "intansv") 
softSearch.file.path
"/tmp/RtmpTNVj6Y/Rinst4ae7115d3df6/intansv/extdata/ZS97.softsearch"
softSearch <- readSoftSearch(softSearch.file.path)
str(softSearch)
```

## Integrate predictions of different programms

```{r, chunk7}
sv_all_methods <- methodsMerge(breakdancer, pindel, cnvnator, delly, svseq)
str(sv_all_methods)
```

## Anotate the effects of SVs

```{r, chunk8}
anno.file.path <- system.file("extdata/chr05_chr10.anno.txt", package = "intansv")
anno.file.path
"/tmp/RtmpTNVj6Y/Rinst4ae7115d3df6/intansv/extdata/chr05_chr10.anno.txt"
msu_gff_v7 <- read.table(anno.file.path, head = TRUE, as.is = TRUE)
head(msu_gff_v7)
```

## Including plots

```{r, plot1}
genome.file.path <- system.file("extdata/chr05_chr10.genome.txt", package = "intansv")
genome.file.path
"/tmp/RtmpTNVj6Y/Rinst4ae7115d3df6/intansv/extdata/chr05_chr10.genome.txt"
genome <- read.table(genome.file.path, head=TRUE, as.is=TRUE)
plotChromosome(genome, sv_all_methods,1000000)
```

```{r, plot2}
head(msu_gff_v7, n = 3)
plotRegion(sv_all_methods,msu_gff_v7, "chr05", 1, 200000)
```

## Session Information

```{r pressure, echo=FALSE}
sessionInfo()
```

